name: Python Linting Validation

on: workflow_call

jobs:
  pylint:
    runs-on: ubuntu-22.04
    steps:
      - name: Code Checkout
        uses: actions/checkout@v3

      - name: Install Pylint
        run: echo "Implement me!"

      - name: Check Linting
        run: echo "Implement me!"
